<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CommandPalette.Extensions" Version="0.12.260812002" />
    <PackageVersion Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4188" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.7.260610101" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Shmuelie.WinRTServer" Version="2.2.1" />
    <PackageVersion Include="xunit.v3.mtp-off" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xiSage.GodotConfigFile" Version="0.3.0" />
    <PackageVersion Include="xiSage.GodotResourceUID" Version="0.1.0" />
  </ItemGroup>
</Project>